### ISSUE TITLE
Make a landing screen

### ISSUE THREAD

**Issue by harshjohar** [harshjohar/Big-Moni#21]
Design a landing screen UI for the new user.
- Add a screen in Landing folder inside the `features` directory of `lib`
- Link this to login system
- Add this navigation to the `main.dart` at the part where we redirect to _LoginScreen_ if user is not signed in

**Comment by SichangiFelix** [comment]
I would like to handle this

**Comment by harshjohar** [comment]
Assigned, Goodluck

**Comment by SichangiFelix** [comment]
Just created a PR for the landing screen

**Comment by harshjohar** [comment]
fixed in #29, thanks @SichangiFelix

**Comment by SichangiFelix** [comment]
your welcome
